import type { NutritionProfile } from "./nutrition.types";

/** Nutrition stories, part 1 of 3. Numbers are per 100g, from USDA FoodData Central reference figures. */
export const NUTRITION_PROFILES_1: Record<string, NutritionProfile> = {
  almond: {
    label: "Almonds",
    urduName: "بادام",
    tagline: "Small in size. Big in nutrition.",
    why: "A nutrient-dense addition to a balanced diet — a small handful brings together protein, fiber and vitamin E.",
    nutrients: [
      { name: "Protein", icon: "dumbbell", value: "21.2g" },
      { name: "Fiber", icon: "wheat-awn", value: "12.5g" },
      { name: "Healthy Fats", icon: "droplet", value: "49.9g" },
      { name: "Vitamin E", icon: "sun", value: "25.6mg" },
    ],
    basis: "Per 100g, raw (USDA reference values)",
    serving: {
      size: "28g (a small handful)",
      calories: "~164 kcal per 28g serving",
      note: "A simple handful can be an easy addition to a balanced diet.",
    },
    didYouKnow: "Almonds are among the richer food sources of vitamin E.",
    tip: "Keep almonds in an airtight container in a cool, dry place to help maintain their freshness.",
    bestFor: [
      { emoji: "🥣", label: "Breakfast" },
      { emoji: "📚", label: "Study & Work" },
      { emoji: "☕", label: "Everyday Snacking" },
      { emoji: "🍰", label: "Baking" },
    ],
  },
  cashew: {
    label: "Cashews",
    urduName: "کاجو",
    tagline: "Naturally creamy. Naturally nourishing.",
    why: "Creamy-textured kernels that naturally contain protein along with minerals like copper and magnesium.",
    nutrients: [
      { name: "Protein", icon: "dumbbell", value: "18.2g" },
      { name: "Copper", icon: "gem", value: "2.2mg" },
      { name: "Magnesium", icon: "mountain", value: "292mg" },
      { name: "Healthy Fats", icon: "droplet", value: "43.9g" },
    ],
    basis: "Per 100g, raw (USDA reference values)",
    serving: {
      size: "28g (a small handful)",
      calories: "~157 kcal per 28g serving",
      note: "A convenient snack option between meals.",
    },
    didYouKnow: "Cashews naturally contain copper and magnesium among their micronutrients.",
    tip: "Store cashews sealed and away from heat — their natural oils stay fresher in a cool, dry cupboard.",
    bestFor: [
      { emoji: "☕", label: "Everyday Snacking" },
      { emoji: "🍛", label: "Cooking & Korma" },
      { emoji: "🎁", label: "Gifting" },
      { emoji: "🍰", label: "Desserts" },
    ],
  },
  pistachio: {
    label: "Pistachios",
    urduName: "پستہ",
    tagline: "A delicious crunch with a naturally balanced nutrition profile.",
    why: "Pistachios pair protein and fiber in one satisfying, shell-cracking snack.",
    nutrients: [
      { name: "Protein", icon: "dumbbell", value: "20.2g" },
      { name: "Fiber", icon: "wheat-awn", value: "10.6g" },
      { name: "Vitamin B6", icon: "bolt", value: "1.7mg" },
      { name: "Healthy Fats", icon: "droplet", value: "45.3g" },
    ],
    basis: "Per 100g, raw kernels (USDA reference values)",
    serving: {
      size: "28g (about 49 kernels)",
      calories: "~159 kcal per 28g serving",
      note: "Cracking the shells naturally slows down snacking.",
    },
    didYouKnow: "Pistachios provide protein and fiber along with a range of micronutrients.",
    tip: "Keep pistachios in a sealed jar — in-shell pistachios hold their crunch longer than shelled kernels.",
    bestFor: [
      { emoji: "☕", label: "Everyday Snacking" },
      { emoji: "🍨", label: "Desserts & Kheer" },
      { emoji: "🎁", label: "Gifting" },
      { emoji: "💪", label: "Active Lifestyle" },
    ],
  },
  walnut: {
    label: "Walnuts",
    urduName: "اخروٹ",
    tagline: "Rich, earthy and naturally packed with healthy fats.",
    why: "Walnuts stand out among nuts for their plant-based ALA omega-3 content.",
    nutrients: [
      { name: "ALA Omega-3", icon: "fish", value: "9.1g" },
      { name: "Fiber", icon: "wheat-awn", value: "6.7g" },
      { name: "Healthy Fats", icon: "droplet", value: "65.2g" },
      { name: "Protein", icon: "dumbbell", value: "15.2g" },
    ],
    basis: "Per 100g, kernels (USDA reference values)",
    serving: {
      size: "28g (about 7 halves)",
      calories: "~185 kcal per 28g serving",
      note: "A classic winter-evening handful.",
    },
    didYouKnow: "Walnuts naturally contain ALA, a plant-based omega-3 fatty acid.",
    tip: "Walnut kernels stay freshest refrigerated in an airtight container, especially in warm months.",
    bestFor: [
      { emoji: "🥣", label: "Breakfast" },
      { emoji: "📚", label: "Study & Work" },
      { emoji: "🍰", label: "Baking" },
      { emoji: "☕", label: "Everyday Snacking" },
    ],
  },
  pinenut: {
    label: "Chilgoza",
    urduName: "چلغوزہ",
    tagline: "Pakistan's rare mountain delicacy, rich by nature.",
    why: "Pine nuts are naturally energy-dense kernels with healthy fats, protein and minerals.",
    nutrients: [
      { name: "Healthy Fats", icon: "droplet", value: "68.4g" },
      { name: "Protein", icon: "dumbbell", value: "13.7g" },
      { name: "Magnesium", icon: "mountain", value: "251mg" },
      { name: "Vitamin K", icon: "leaf", value: "53.9µg" },
    ],
    basis: "Per 100g, dried kernels (USDA reference values)",
    serving: {
      size: "28g (a small handful)",
      calories: "~191 kcal per 28g serving",
      note: "A little goes a long way with this prized nut.",
    },
    didYouKnow:
      "Chilgoza pine nuts are harvested largely by hand from high-altitude forests — one reason they are among the priciest nuts in the world.",
    tip: "Store chilgoza sealed in a cool place and enjoy within weeks of roasting — their delicate oils are best fresh.",
    bestFor: [
      { emoji: "❄️", label: "Winter Evenings" },
      { emoji: "🎁", label: "Premium Gifting" },
      { emoji: "🍚", label: "Pilaf & Cooking" },
      { emoji: "☕", label: "Special Occasions" },
    ],
  },
  peanut: {
    label: "Peanuts",
    urduName: "مونگ پھلی",
    tagline: "The humble handful that never goes out of season.",
    why: "An affordable, protein-forward snack loved across Pakistan every winter.",
    nutrients: [
      { name: "Protein", icon: "dumbbell", value: "25.8g" },
      { name: "Fiber", icon: "wheat-awn", value: "8.5g" },
      { name: "Niacin (B3)", icon: "bolt", value: "12.1mg" },
      { name: "Healthy Fats", icon: "droplet", value: "49.2g" },
    ],
    basis: "Per 100g, raw (USDA reference values)",
    serving: {
      size: "28g (a small handful)",
      calories: "~161 kcal per 28g serving",
      note: "A convenient everyday snack option.",
    },
    didYouKnow: "Gram for gram, peanuts contain more protein than most tree nuts.",
    tip: "Keep roasted peanuts sealed once opened so they hold their crunch and toasty flavor.",
    bestFor: [
      { emoji: "❄️", label: "Winter Evenings" },
      { emoji: "📚", label: "Study & Work" },
      { emoji: "☕", label: "Everyday Snacking" },
      { emoji: "💪", label: "Active Lifestyle" },
    ],
  },
  hazelnut: {
    label: "Hazelnuts",
    urduName: "فندق",
    tagline: "Sweet, toasty and quietly nutritious.",
    why: "Aromatic kernels that naturally contain vitamin E and healthy fats.",
    nutrients: [
      { name: "Vitamin E", icon: "sun", value: "15mg" },
      { name: "Healthy Fats", icon: "droplet", value: "60.8g" },
      { name: "Protein", icon: "dumbbell", value: "15g" },
      { name: "Manganese", icon: "gem", value: "6.2mg" },
    ],
    basis: "Per 100g, raw (USDA reference values)",
    serving: {
      size: "28g (about 21 nuts)",
      calories: "~178 kcal per 28g serving",
      note: "Lovely on their own or folded into desserts.",
    },
    didYouKnow:
      "Hazelnuts and chocolate became famous companions, but the nut is a rich snack entirely on its own.",
    tip: "Store hazelnuts in an airtight container away from light to keep their sweet aroma.",
    bestFor: [
      { emoji: "🍰", label: "Baking" },
      { emoji: "🍫", label: "Desserts" },
      { emoji: "☕", label: "Everyday Snacking" },
      { emoji: "🎁", label: "Gifting" },
    ],
  },
  macadamia: {
    label: "Macadamia",
    urduName: "میکاڈیمیا",
    tagline: "The creamiest bite in the nut world.",
    why: "Naturally the most buttery of nuts, with predominantly monounsaturated fats.",
    nutrients: [
      { name: "Healthy Fats", icon: "droplet", value: "75.8g" },
      { name: "Fiber", icon: "wheat-awn", value: "8.6g" },
      { name: "Manganese", icon: "gem", value: "4.1mg" },
      { name: "Thiamin (B1)", icon: "bolt", value: "1.2mg" },
    ],
    basis: "Per 100g, raw (USDA reference values)",
    serving: {
      size: "28g (about 11 nuts)",
      calories: "~204 kcal per 28g serving",
      note: "An indulgent treat — a few go a long way.",
    },
    didYouKnow:
      "Most of the fat in macadamias is monounsaturated — the same broad family found in olive oil.",
    tip: "Refrigerate macadamias in a sealed jar; their rich oils are delicate and stay freshest cold.",
    bestFor: [
      { emoji: "🎁", label: "Premium Gifting" },
      { emoji: "🍰", label: "Baking" },
      { emoji: "☕", label: "Special Occasions" },
      { emoji: "🥣", label: "Breakfast Bowls" },
    ],
  },
  brazil: {
    label: "Brazil Nuts",
    urduName: "برازیل نٹ",
    tagline: "Big kernels with a naturally rich character.",
    why: "Large Amazon-origin kernels naturally notable for the mineral selenium.",
    nutrients: [
      { name: "Selenium", icon: "gem", value: "Notably rich" },
      { name: "Healthy Fats", icon: "droplet", value: "67.1g" },
      { name: "Protein", icon: "dumbbell", value: "14.3g" },
      { name: "Magnesium", icon: "mountain", value: "376mg" },
    ],
    basis: "Per 100g, raw (USDA reference values)",
    serving: {
      size: "28g (about 6 nuts)",
      calories: "~187 kcal per 28g serving",
      note: "Because they are naturally very rich in selenium, small servings are the norm.",
    },
    didYouKnow:
      "Brazil nuts are among the most concentrated common food sources of selenium — a little truly is enough.",
    tip: "Keep Brazil nuts sealed and cool; buy in small quantities and enjoy them fresh.",
    bestFor: [
      { emoji: "☕", label: "Occasional Snacking" },
      { emoji: "🥣", label: "Breakfast Bowls" },
      { emoji: "🎁", label: "Gifting" },
      { emoji: "🍰", label: "Baking" },
    ],
  },
};
