import type { NutritionProfile } from "./nutrition.types";

/** Nutrition stories, part 3 of 3. Numbers are per 100g, from USDA FoodData Central reference figures. */
export const NUTRITION_PROFILES_3: Record<string, NutritionProfile> = {
  pumpkinseed: {
    label: "Pumpkin Seeds",
    urduName: "کدو کے بیج",
    tagline: "Small seeds, generous nutrition.",
    why: "Pepitas are naturally protein-dense for their size, with magnesium and healthy fats.",
    nutrients: [
      { name: "Protein", icon: "dumbbell", value: "30.2g" },
      { name: "Magnesium", icon: "mountain", value: "592mg" },
      { name: "Healthy Fats", icon: "droplet", value: "49g" },
      { name: "Zinc", icon: "shield", value: "7.8mg" },
    ],
    basis: "Per 100g, hulled kernels (USDA reference values)",
    serving: {
      size: "2 tablespoons (approx. 20g)",
      calories: "~115 kcal per 20g serving",
      note: "Sprinkle over salads, yogurt or soups.",
    },
    didYouKnow: "Among common seeds, pumpkin seeds are notably concentrated in magnesium.",
    tip: "Store seeds airtight and cool; lightly re-toast in a dry pan to revive their crunch.",
    bestFor: [
      { emoji: "🥗", label: "Salads" },
      { emoji: "🥣", label: "Breakfast Bowls" },
      { emoji: "💪", label: "Active Lifestyle" },
      { emoji: "☕", label: "Everyday Snacking" },
    ],
  },
  chia: {
    label: "Chia Seeds",
    urduName: "چیا سیڈز",
    tagline: "Tiny seeds with a remarkable fiber story.",
    why: "Chia seeds are exceptionally fiber-dense and naturally contain plant omega-3 (ALA).",
    nutrients: [
      { name: "Fiber", icon: "wheat-awn", value: "34.4g" },
      { name: "ALA Omega-3", icon: "fish", value: "17.8g" },
      { name: "Protein", icon: "dumbbell", value: "16.5g" },
      { name: "Calcium", icon: "bone", value: "631mg" },
    ],
    basis: "Per 100g, dried (USDA reference values)",
    serving: {
      size: "1–2 tablespoons (approx. 15g)",
      calories: "~73 kcal per 15g serving",
      note: "Soak before use — chia absorbs many times its weight in liquid.",
    },
    didYouKnow:
      "Chia seeds can absorb roughly 10 times their weight in water, forming a natural gel.",
    tip: "Keep chia in a sealed dry jar; unlike many seeds it stores well for months at room temperature.",
    bestFor: [
      { emoji: "🥤", label: "Smoothies" },
      { emoji: "🥣", label: "Puddings & Yogurt" },
      { emoji: "🥗", label: "Sprinkling" },
      { emoji: "💪", label: "Active Lifestyle" },
    ],
  },
  flax: {
    label: "Flax Seeds",
    urduName: "السی",
    tagline: "An old desi staple with modern appeal.",
    why: "Alsi seeds naturally contain fiber and ALA, the plant-based omega-3 fatty acid.",
    nutrients: [
      { name: "Fiber", icon: "wheat-awn", value: "27.3g" },
      { name: "ALA Omega-3", icon: "fish", value: "22.8g" },
      { name: "Protein", icon: "dumbbell", value: "18.3g" },
      { name: "Lignans", icon: "leaf", value: "Present" },
    ],
    basis: "Per 100g, whole seeds (USDA reference values)",
    serving: {
      size: "1 tablespoon (approx. 10g)",
      calories: "~53 kcal per 10g serving",
      note: "Traditionally roasted, or ground fresh before use.",
    },
    didYouKnow:
      "Flax is one of the oldest cultivated crops — grown for both its seed and its fiber for thousands of years.",
    tip: "Grind flax just before use and refrigerate any ground surplus; whole seeds keep far longer.",
    bestFor: [
      { emoji: "🥣", label: "Breakfast" },
      { emoji: "🍞", label: "Baking" },
      { emoji: "🥤", label: "Smoothies" },
      { emoji: "❄️", label: "Winter Pinnis" },
    ],
  },
  sunflower: {
    label: "Sunflower Seeds",
    urduName: "سورج مکھی کے بیج",
    tagline: "Mild, crunchy and endlessly versatile.",
    why: "Sunflower kernels naturally contain vitamin E and protein in a budget-friendly seed.",
    nutrients: [
      { name: "Vitamin E", icon: "sun", value: "35.2mg" },
      { name: "Protein", icon: "dumbbell", value: "20.8g" },
      { name: "Healthy Fats", icon: "droplet", value: "51.5g" },
      { name: "Fiber", icon: "wheat-awn", value: "8.6g" },
    ],
    basis: "Per 100g, hulled kernels (USDA reference values)",
    serving: {
      size: "2 tablespoons (approx. 20g)",
      calories: "~117 kcal per 20g serving",
      note: "Great toasted over salads or straight from the pack.",
    },
    didYouKnow: "Sunflower kernels are among the more concentrated everyday sources of vitamin E.",
    tip: "Keep kernels sealed and cool — their delicate oils fade fastest in warm, open air.",
    bestFor: [
      { emoji: "🥗", label: "Salads" },
      { emoji: "🥣", label: "Breakfast Bowls" },
      { emoji: "☕", label: "Everyday Snacking" },
      { emoji: "🍞", label: "Baking" },
    ],
  },
  melonseed: {
    label: "Melon Seeds",
    urduName: "مغز",
    tagline: "The delicate magaz of traditional kitchens.",
    why: "Hand-peeled melon kernels naturally contain protein and plant fats, prized in desi sweets and sherbets.",
    nutrients: [
      { name: "Protein", icon: "dumbbell", value: "Naturally rich" },
      { name: "Plant Fats", icon: "droplet", value: "Naturally rich" },
      { name: "Magnesium", icon: "mountain", value: "Present" },
      { name: "Zinc", icon: "shield", value: "Present" },
    ],
    basis: "Naturally contains (values vary by seed blend)",
    serving: {
      size: "1–2 tablespoons (approx. 15g)",
      calories: "",
      note: "Traditionally used in sardai, sweets and garnishes.",
    },
    didYouKnow:
      "Magaz — the mixed kernels of melon family seeds — has flavored South Asian sherbets and sweets for generations.",
    tip: "Magaz is delicate: keep it refrigerated in a sealed jar and use it fresh.",
    bestFor: [
      { emoji: "🥤", label: "Sherbets & Sardai" },
      { emoji: "🍮", label: "Traditional Sweets" },
      { emoji: "🍰", label: "Garnishing" },
      { emoji: "❄️", label: "Winter Recipes" },
    ],
  },
  chana: {
    label: "Roasted Chana",
    urduName: "بھنے چنے",
    tagline: "Pakistan's original high-fiber snack.",
    why: "Roasted chickpeas are a naturally filling snack with plant protein and fiber — no frying involved.",
    nutrients: [
      { name: "Protein", icon: "dumbbell", value: "Naturally rich" },
      { name: "Fiber", icon: "wheat-awn", value: "Naturally rich" },
      { name: "Carbohydrates", icon: "bolt", value: "Present" },
      { name: "Iron", icon: "gem", value: "Present" },
    ],
    basis: "Naturally contains (values vary by roasting and skin)",
    serving: {
      size: "A handful (approx. 30g)",
      calories: "",
      note: "A convenient, budget-friendly everyday snack option.",
    },
    didYouKnow: "Bhuna chana is dry-roasted, not fried — the crunch comes entirely from the roast.",
    tip: "Keep chana in a dry, airtight jar; a few seconds in a hot pan brings back full crispness.",
    bestFor: [
      { emoji: "📚", label: "Study & Work" },
      { emoji: "💪", label: "Active Lifestyle" },
      { emoji: "☕", label: "Everyday Snacking" },
      { emoji: "🎒", label: "Lunchboxes" },
    ],
  },
  makhana: {
    label: "Makhana",
    urduName: "مکھانہ",
    tagline: "Cloud-light crunch from the lotus pond.",
    why: "Fox nuts are a light, low-oil snack that carries carbohydrates and protein with very little fat.",
    nutrients: [
      { name: "Carbohydrates", icon: "bolt", value: "Naturally rich" },
      { name: "Protein", icon: "dumbbell", value: "Present" },
      { name: "Low Fat", icon: "feather", value: "Naturally light" },
      { name: "Minerals", icon: "gem", value: "Present" },
    ],
    basis: "Naturally contains (values vary by roasting)",
    serving: {
      size: "A bowl (approx. 25g)",
      calories: "",
      note: "Roast with a little ghee and rock salt for the classic taste.",
    },
    didYouKnow: "Makhana comes from the seeds of the prickly water lily, popped much like corn.",
    tip: "Makhana softens quickly in open air — store sealed and re-crisp in a dry pan before serving.",
    bestFor: [
      { emoji: "🌙", label: "Light Evening Snacking" },
      { emoji: "🍮", label: "Kheer" },
      { emoji: "📿", label: "Fasting Days" },
      { emoji: "🎒", label: "Lunchboxes" },
    ],
  },
  mix: {
    label: "Mixed Dry Fruits",
    urduName: "مکس میوہ جات",
    tagline: "A balanced handful of everything good.",
    why: "A well-made mix combines the different natural strengths of nuts, dried fruits and seeds in one scoop.",
    nutrients: [
      { name: "Protein", icon: "dumbbell", value: "From the nuts" },
      { name: "Fiber", icon: "wheat-awn", value: "From fruit & nuts" },
      { name: "Healthy Fats", icon: "droplet", value: "From the nuts" },
      { name: "Natural Sugars", icon: "cubes-stacked", value: "From the fruit" },
    ],
    basis: "Nutrition varies according to the exact mixture",
    serving: {
      size: "A handful (approx. 30g)",
      calories: "",
      note: "The exact profile depends on the blend in your pack.",
    },
    didYouKnow:
      "Mixing nuts with dried fruit balances rich and sweet — a trick bazaar traders have used for generations.",
    tip: "Give the jar a gentle shake before serving so heavier nuts and lighter fruit stay evenly mixed.",
    bestFor: [
      { emoji: "🥾", label: "Travel & Hiking" },
      { emoji: "📚", label: "Study & Work" },
      { emoji: "🏠", label: "Family Bowls" },
      { emoji: "🎁", label: "Gifting" },
    ],
  },
  gift: {
    label: "Gift Assortments",
    urduName: "گفٹ باکس",
    tagline: "A curated spread of nature's finest.",
    why: "Each gift box brings together several products, so the nutrition story is a blend of everything inside.",
    nutrients: [
      { name: "Protein", icon: "dumbbell", value: "From the nuts" },
      { name: "Fiber", icon: "wheat-awn", value: "From fruit & nuts" },
      { name: "Healthy Fats", icon: "droplet", value: "From the nuts" },
      { name: "Natural Sugars", icon: "cubes-stacked", value: "From the dates & fruit" },
    ],
    basis: "Nutrition varies according to the exact assortment",
    serving: {
      size: "Varies by item inside the box",
      calories: "",
      note: "Every compartment tells its own story.",
    },
    didYouKnow:
      "Dry fruit has been a gift of honor in Pakistani homes for generations — offered to guests before anything else.",
    tip: "Once opened, transfer contents to airtight jars to keep each item at its freshest.",
    bestFor: [
      { emoji: "🎁", label: "Gifting" },
      { emoji: "💍", label: "Weddings" },
      { emoji: "🌙", label: "Eid & Ramadan" },
      { emoji: "🏢", label: "Corporate" },
    ],
  },
};
