import type { NutritionProfile } from "./nutrition.types";

/** Nutrition stories, part 2 of 3. Numbers are per 100g, from USDA FoodData Central reference figures. */
export const NUTRITION_PROFILES_2: Record<string, NutritionProfile> = {
  dates: {
    label: "Dates",
    urduName: "کھجور",
    tagline: "Naturally sweet energy from one of nature's classic fruits.",
    why: "Dates deliver natural sweetness with fiber and potassium — no added sugar needed.",
    nutrients: [
      { name: "Carbohydrates", icon: "bolt", value: "75g" },
      { name: "Fiber", icon: "wheat-awn", value: "6.7g" },
      { name: "Potassium", icon: "heart", value: "696mg" },
      { name: "Natural Sugars", icon: "cubes-stacked", value: "66g" },
    ],
    basis: "Per 100g, Medjool dates (USDA reference values)",
    serving: {
      size: "2–3 dates (approx. 40g)",
      calories: "~110 kcal per 40g serving",
      note: "A traditional way to open iftar and a naturally sweet pick-me-up.",
    },
    didYouKnow:
      "Dates are naturally sweet fruits and provide carbohydrates and fiber — their sweetness comes entirely from the fruit itself.",
    tip: "Keep dates in a sealed container; refrigeration keeps soft varieties like Ajwa and Mazafati at their best.",
    bestFor: [
      { emoji: "🥣", label: "Breakfast" },
      { emoji: "💪", label: "Active Lifestyle" },
      { emoji: "☕", label: "Everyday Snacking" },
      { emoji: "🎁", label: "Gifting" },
    ],
  },
  drydates: {
    label: "Dry Dates",
    urduName: "چھوہارا",
    tagline: "The firm, golden classic of desi kitchens.",
    why: "Sun-dried chuhara concentrates the date's natural carbohydrates into a long-lasting pantry staple.",
    nutrients: [
      { name: "Carbohydrates", icon: "bolt", value: "Naturally rich" },
      { name: "Fiber", icon: "wheat-awn", value: "Present" },
      { name: "Potassium", icon: "heart", value: "Present" },
      { name: "Natural Sugars", icon: "cubes-stacked", value: "Concentrated" },
    ],
    basis: "Naturally contains (values vary by variety and drying)",
    serving: {
      size: "2–3 pieces (approx. 25g)",
      calories: "",
      note: "Traditionally simmered in milk or added to desserts.",
    },
    didYouKnow:
      "Chuhara is simply date fruit dried until firm — the same fruit, concentrated by the sun.",
    tip: "Chuhara stores well for months in a dry, airtight jar away from humidity.",
    bestFor: [
      { emoji: "🥛", label: "Doodh Chuhara" },
      { emoji: "🍚", label: "Traditional Recipes" },
      { emoji: "❄️", label: "Winter Use" },
      { emoji: "🎁", label: "Gifting" },
    ],
  },
  fig: {
    label: "Anjeer",
    urduName: "انجیر",
    tagline: "Naturally sweet, chewy and a delicious source of fiber.",
    why: "Dried figs are one of the more fiber-dense dried fruits, with calcium and potassium alongside.",
    nutrients: [
      { name: "Fiber", icon: "wheat-awn", value: "9.8g" },
      { name: "Carbohydrates", icon: "bolt", value: "63.9g" },
      { name: "Calcium", icon: "bone", value: "162mg" },
      { name: "Potassium", icon: "heart", value: "680mg" },
    ],
    basis: "Per 100g, dried figs (USDA reference values)",
    serving: {
      size: "2–3 figs (approx. 40g)",
      calories: "~100 kcal per 40g serving",
      note: "Delicious on their own or soaked overnight.",
    },
    didYouKnow: "Among dried fruits, anjeer is notable for containing calcium as well as fiber.",
    tip: "Protect anjeer from moisture — a sealed jar in a cool cupboard keeps the figs soft and chewy.",
    bestFor: [
      { emoji: "🥣", label: "Breakfast" },
      { emoji: "☕", label: "Everyday Snacking" },
      { emoji: "🥛", label: "With Milk" },
      { emoji: "🎁", label: "Gifting" },
    ],
  },
  apricot: {
    label: "Apricots",
    urduName: "خوبانی",
    tagline: "Sun-dried gold from the northern valleys.",
    why: "Hunza's famous khubani concentrates the fruit's natural sweetness, fiber and potassium.",
    nutrients: [
      { name: "Fiber", icon: "wheat-awn", value: "7.3g" },
      { name: "Carbohydrates", icon: "bolt", value: "62.6g" },
      { name: "Potassium", icon: "heart", value: "1162mg" },
      { name: "Vitamin A", icon: "eye", value: "Present" },
    ],
    basis: "Per 100g, dried apricots (USDA reference values)",
    serving: {
      size: "4–5 pieces (approx. 40g)",
      calories: "~96 kcal per 40g serving",
      note: "A tangy-sweet snack straight from the pack.",
    },
    didYouKnow:
      "In the northern valleys, apricots are traditionally dried on rooftops under the summer sun.",
    tip: "Keep khubani sealed and dry; a cool cupboard preserves its chewy texture and tang.",
    bestFor: [
      { emoji: "🥣", label: "Breakfast" },
      { emoji: "🥾", label: "Hiking & Travel" },
      { emoji: "☕", label: "Everyday Snacking" },
      { emoji: "🍰", label: "Baking" },
    ],
  },
  raisin: {
    label: "Raisins",
    urduName: "کشمش",
    tagline: "Little bursts of natural sweetness.",
    why: "Raisins are dried grapes — naturally sweet, portable carbohydrate energy with some fiber.",
    nutrients: [
      { name: "Carbohydrates", icon: "bolt", value: "79.2g" },
      { name: "Fiber", icon: "wheat-awn", value: "3.7g" },
      { name: "Potassium", icon: "heart", value: "749mg" },
      { name: "Natural Sugars", icon: "cubes-stacked", value: "59g" },
    ],
    basis: "Per 100g, seedless raisins (USDA reference values)",
    serving: {
      size: "A small box or handful (approx. 40g)",
      calories: "~120 kcal per 40g serving",
      note: "Easy to sprinkle over almost anything.",
    },
    didYouKnow: "All the sweetness in kishmish comes from the grape itself — nothing is added.",
    tip: "Store kishmish airtight away from humidity so the raisins stay soft instead of crystallizing.",
    bestFor: [
      { emoji: "🍚", label: "Pulao & Zarda" },
      { emoji: "🥣", label: "Breakfast" },
      { emoji: "☕", label: "Everyday Snacking" },
      { emoji: "🍰", label: "Baking" },
    ],
  },
  prune: {
    label: "Prunes",
    urduName: "آلو بخارا",
    tagline: "Deep, jammy and naturally fiber-rich.",
    why: "Dried plums are well known for their fiber content and rich, mellow sweetness.",
    nutrients: [
      { name: "Fiber", icon: "wheat-awn", value: "7.1g" },
      { name: "Carbohydrates", icon: "bolt", value: "63.9g" },
      { name: "Potassium", icon: "heart", value: "732mg" },
      { name: "Vitamin K", icon: "leaf", value: "59.5µg" },
    ],
    basis: "Per 100g, dried plums (USDA reference values)",
    serving: {
      size: "3–4 prunes (approx. 40g)",
      calories: "~96 kcal per 40g serving",
      note: "Enjoy as-is or chopped into porridge.",
    },
    didYouKnow: "Prunes are simply plums dried whole — their concentrated fiber made them famous.",
    tip: "Keep prunes sealed after opening; they stay moist longest in a cool, dry spot.",
    bestFor: [
      { emoji: "🥣", label: "Breakfast" },
      { emoji: "🍛", label: "Cooking" },
      { emoji: "☕", label: "Everyday Snacking" },
      { emoji: "🍰", label: "Baking" },
    ],
  },
  driedfruit: {
    label: "Dried Fruit",
    urduName: "خشک میوہ",
    tagline: "Fruit's natural sweetness, ready anywhere.",
    why: "Drying concentrates the fruit's natural sugars and fiber into a convenient, portable snack.",
    nutrients: [
      { name: "Carbohydrates", icon: "bolt", value: "Naturally rich" },
      { name: "Fiber", icon: "wheat-awn", value: "Present" },
      { name: "Natural Sugars", icon: "cubes-stacked", value: "From the fruit" },
      { name: "Micronutrients", icon: "gem", value: "Vary by fruit" },
    ],
    basis: "Naturally contains (values vary by fruit and processing)",
    serving: {
      size: "A small serving (approx. 30–40g)",
      calories: "",
      note: "A convenient alternative to sugary packaged snacks.",
    },
    didYouKnow:
      "Because water is removed, dried fruit is naturally more concentrated than fresh fruit — smaller servings feel just as satisfying.",
    tip: "Protect dried fruit from moisture and heat; an airtight jar keeps the texture right.",
    bestFor: [
      { emoji: "🥾", label: "Travel" },
      { emoji: "☕", label: "Everyday Snacking" },
      { emoji: "🥣", label: "Breakfast" },
      { emoji: "🍰", label: "Baking" },
    ],
  },
  coconut: {
    label: "Coconut",
    urduName: "ناریل",
    tagline: "Crisp, naturally sweet and satisfying.",
    why: "Dried coconut is naturally rich in fiber and plant fats with gentle sweetness of its own.",
    nutrients: [
      { name: "Fiber", icon: "wheat-awn", value: "Naturally rich" },
      { name: "Plant Fats", icon: "droplet", value: "Naturally rich" },
      { name: "Manganese", icon: "gem", value: "Present" },
      { name: "Carbohydrates", icon: "bolt", value: "Present" },
    ],
    basis: "Naturally contains (values vary by cut and drying)",
    serving: {
      size: "A few slices (approx. 20–30g)",
      calories: "",
      note: "A crisp nibble with tea or in desserts.",
    },
    didYouKnow: "Dried coconut — khopra — has been a staple of South Asian sweets for centuries.",
    tip: "Keep coconut slices tightly sealed; they readily absorb moisture and aromas from the kitchen.",
    bestFor: [
      { emoji: "🍰", label: "Desserts" },
      { emoji: "☕", label: "With Tea" },
      { emoji: "🍛", label: "Cooking" },
      { emoji: "🥣", label: "Breakfast Bowls" },
    ],
  },
  banana: {
    label: "Banana Chips",
    urduName: "کیلے کے چپس",
    tagline: "Golden crunch, straight from the fruit bowl.",
    why: "A crunchy fruit snack that delivers carbohydrates in lunchbox-friendly form.",
    nutrients: [
      { name: "Carbohydrates", icon: "bolt", value: "Naturally rich" },
      { name: "Fiber", icon: "wheat-awn", value: "Present" },
      { name: "Potassium", icon: "heart", value: "Present" },
      { name: "Natural Sugars", icon: "cubes-stacked", value: "From the fruit" },
    ],
    basis: "Naturally contains (values vary by preparation)",
    serving: {
      size: "A small handful (approx. 30g)",
      calories: "",
      note: "A crunchy treat kids reliably approve of.",
    },
    didYouKnow:
      "Banana chips are typically made from firm, starchy bananas sliced and dried or fried until crisp.",
    tip: "Reseal the pack well after opening — banana chips lose their snap quickly in humid air.",
    bestFor: [
      { emoji: "🎒", label: "Lunchboxes" },
      { emoji: "🥾", label: "Travel" },
      { emoji: "☕", label: "Everyday Snacking" },
      { emoji: "🎬", label: "Movie Nights" },
    ],
  },
};
